const Data = [
	{
		id: "1",
		image: require("./asset/profile1.png"),
		name: "Achmad Hilmy",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "2",
		image: require("./asset/profile2.png"),
		name: "Josep",
		message: "sep main kuy",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "3",
		image: require("./asset/profile3.png"),
		name: "Davidd",
		message: "tidak boleh begitu",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "4",
		image: require("./asset/profile1.png"),
		name: "Josh",
		message: "kuy",
		time: "13.00",
		totalMessage: "2",
	},
	{
		id: "5",
		image: require("./asset/profile2.png"),
		name: "Mike",
		message: "besok bae dah ",
		time: "01.00",
		totalMessage: "4",
	},
	{
		id: "6",
		image: require("./asset/profile3.png"),
		name: "Lord",
		message: "gw sendiri",
		time: "02.00",
		totalMessage: "1",
	},
	{
		id: "7",
		image: require("./asset/profile1.png"),
		name: "Drake",
		message: "iyee serah",
		time: "12.00",
		totalMessage: "2",
	},
	{
		id: "8",
		image: require("./asset/profile2.png"),
		name: "Lemy",
		message: "laper dah gw",
		time: "12.00",
		totalMessage: "4",
	},
	{
		id: "9",
		image: require("./asset/profile3.png"),
		name: "KOKO",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "1",
	},
	{
		id: "10",
		image: require("./asset/profile1.png"),
		name: "Gojekk",
		message: "Hello Achmad Hilmy",
		time: "12.00",
		totalMessage: "2",
	},
	// {
	// 	id: "11",
	// 	image: require("./asset/profile1.png"),
	// 	name: "Achmad Hilmy",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "2",
	// },
	// {
	// 	id: "12",
	// 	image: require("./asset/profile2.png"),
	// 	name: "Profile 2",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "4",
	// },
	// {
	// 	id: "13",
	// 	image: require("./asset/profile3.png"),
	// 	name: "Profile 3",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "1",
	// },
	// {
	// 	id: "14",
	// 	image: require("./asset/profile1.png"),
	// 	name: "Achmad Hilmy",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "2",
	// },
	// {
	// 	id: "15",
	// 	image: require("./asset/profile2.png"),
	// 	name: "Profile 2",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "4",
	// },
	// {
	// 	id: "16",
	// 	image: require("./asset/profile3.png"),
	// 	name: "Profile 3",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "1",
	// },
	// {
	// 	id: "17",
	// 	image: require("./asset/profile1.png"),
	// 	name: "Achmad Hilmy",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "2",
	// },
	// {
	// 	id: "18",
	// 	image: require("./asset/profile2.png"),
	// 	name: "Profile 2",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "4",
	// },
	// {
	// 	id: "19",
	// 	image: require("./asset/profile3.png"),
	// 	name: "Profile 3",
	// 	message: "Hello Achmad Hilmy",
	// 	time: "12.00",
	// 	totalMessage: "1",
	// },
];

export default Data;